# Generated by Django 4.2.3 on 2023-07-14 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="PROCost",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Cost"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="PROCreated",
            field=models.DateTimeField(verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="product",
            name="PRODesc",
            field=models.TextField(verbose_name="Product Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="PROName",
            field=models.CharField(max_length=100, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="PROPrice",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Price"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PROIImage",
                    models.ImageField(upload_to="product/", verbose_name="Image"),
                ),
                (
                    "PROIProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
    ]
