# Generated by Django 4.2.3 on 2023-07-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_procost_alter_product_procreated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CATName", models.CharField(max_length=50, verbose_name="Name")),
                ("CATDesc", models.TextField(verbose_name="Description")),
                (
                    "CATImg",
                    models.ImageField(upload_to="category/", verbose_name="Image"),
                ),
                (
                    "CATParent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                        verbose_name="Main Parent",
                    ),
                ),
            ],
        ),
    ]
