# Generated by Django 4.2.3 on 2023-07-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
        ("product", "0004_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="PRDBrand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.brand",
                verbose_name="Brand ",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="PRDCategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category",
                verbose_name="Category ",
            ),
        ),
    ]
