# Generated by Django 4.2.3 on 2023-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_prdbrand_product_prdcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="PRDImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="prodcut/", verbose_name="Image"
            ),
        ),
    ]
