# Generated by Django 4.2.3 on 2023-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_product_prdimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="PRDSLug",
            field=models.SlugField(blank=True, null=True, verbose_name="Product URL"),
        ),
    ]
